---
framework: "jasmine"
postMerge:
  pattern:
    - "./test/weex/**/*spec.js"
preMerge:
  pattern:
    - "./test/weex/**/*spec.js"
preRun:
  - npm install
postRun:
  - node --version
  - node --version
configFile: "./test/weex/jasmine.js"
version: 1.0
